### ISSUE TITLE
Missing bars on some unique stats

### ISSUE THREAD

**Issue by worldendDominator** [Lailloken/Lailloken-UI#166]
When I use item info on uniques, some items are consistently missing bars for specific stat rolls. Examples in images.
![изображение](https://user-images.githubusercontent.com/6707627/208241999-f2706ff2-fe72-4027-93d6-76685b9190e0.png)
![изображение](https://user-images.githubusercontent.com/6707627/208242292-a2a3b47f-00eb-4652-955c-1e882ececae1.png)
![изображение](https://user-images.githubusercontent.com/6707627/208242380-3d138a11-2d9c-49b3-ba6c-4d6fb7da47bf.png)
Note that other cases of life regen have their bars.

**Comment by Lailloken** [comment]
Thanks for reporting and also including screenshots, very helpful. Yeah, there are a few edge cases I was prepared to tweak manually. I thought I fixed the first case already (it gets thrown off by the numerical value of the stat requirement), but I don't know what's wrong with the other two. The second one might be a rounding error since it's almost bottom roll.

**Comment by worldendDominator** [comment]
For the second one, I have another copy with almost perfect roll and it's still missing the bar.

**Comment by Lailloken** [comment]
v1.29.4-hotfix2 fixes these issues.

**Comment by worldendDominator** [comment]
A similar case, with the bar being full when it shouldn't.
![изображение](https://user-images.githubusercontent.com/6707627/209478632-24536f50-8e5b-4515-a0fb-b47b2aeb210f.png)

**Comment by worldendDominator** [comment]
![изображение](https://user-images.githubusercontent.com/6707627/229997758-a7d9b316-f30d-45ba-b91e-17706d638136.png)
Another case, missing bar in the last stat.

**Comment by Lailloken** [comment]
As always, much appreciated. Will be fixed in the next release, hopefully out later today.
![image](https://user-images.githubusercontent.com/61888437/230015802-6e3e9d41-4561-4687-9a05-59b281832714.png)
