### ISSUE TITLE
SC00 key not found

### ISSUE THREAD

**Issue by t525ooo** [Lailloken/Lailloken-UI#684]
Hi, thank you for this awesome tool! It's my first time using it, and I followed the guide step by step. Unfortunately, after activating the tracker from the menu, I received an error message.

It says that the key "SC00" does not exist. Do you know how to fix this issue?

I'm using AutoHotkey v1.1 with the latest version of the tool.The app is a fresh installation. I haven't modified any settings.

<img width="397" height="485" alt="Image" src="https://github.com/user-attachments/assets/ba83e2d7-b7d5-4378-9a1e-fa2de89d963e" />

**Comment by t525ooo** [comment]
Apologies for the misleading folder name. I've been using LLKUI since version 1.29.6 and really appreciate the tool.
Just to be safe, I re-downloaded the tool, but unfortunately the same error still occurs.

<img width="403" height="482" alt="Image" src="https://github.com/user-attachments/assets/b94883a4-bfe9-4d12-97b9-d485d537bc8e" />

**Comment by t525ooo** [comment]
Thanks for the help. 
After setting 
[hotkeys] 
omni-hotkey="F9", 
the error was resolved and the tool is now functioning as expected. I'm excited for the new league launch!

**Comment by Lailloken** [comment]
What are your locale settings in Windows? It's possible CAPSLOCK is locale-sensitive and doesn't resolve into a proper keyboard-scancode in certain languages.

**Comment by t525ooo** [comment]
I'm using a Japanese locale on Windows11.
